--�����û���
create table users (
	user_id             number
		generated by default as identity start with 1
	primary key,
	username            varchar2(50) not null unique,
	password            varchar2(50) not null,
	email               varchar2(100) not null unique,
	registration_date   date default sysdate,
	user_status         varchar2(20) default 'active',
	gender              varchar2(20),
	bio                 varchar2(20),
	avatar              clob,
	user_role           varchar2(20) default 'user',
	language_preference varchar2(20) default 'chinese'
);

--����ֲ���
create table plants (
	plant_id           number
		generated by default as identity start with 1
	primary key,
	common_name        varchar2(100),
	scientific_name    varchar2(100),
	category           varchar2(100),
	portrayal          clob,
	growth_environment varchar2(255),
	care_conditions    clob
);

--�������۱�
create table comments (
	comment_id      number
		generated by default as identity start with 1
	primary key,
	user_id         number
		references users ( user_id ),
	plant_id        number
		references plants ( plant_id ),
	comment_content clob,
	created_date    date default sysdate
);

--����˽�ű�
create table messages (
	message_id      number
		generated by default as identity start with 1
	primary key,
	sender_id       number
		references users ( user_id ),
	receiver_id     number
		references users ( user_id ),
	message_content clob,
	sent_date       date default sysdate
);

--�����ղر�
create table favorites (
	favorite_id number
		generated by default as identity start with 1
	primary key,
	user_id     number
		references users ( user_id ),
	plant_id    number
		references plants ( plant_id )
);

--�������º͹����
create table articles (
	article_id      number
		generated by default as identity start with 1
	primary key,
	article_title   varchar2(200),
	article_content clob,
	publisher_id    number
		references users ( user_id ),
	published_date  date default sysdate,
	article_type    varchar2(50) default 'article'  -- 'article' or 'announcement'
);

--������˱�
create table reviews (
	review_id        number
		generated by default as identity start with 1
	primary key,
	plant_id         number
		references plants ( plant_id ),
	submitter_id     number
		references users ( user_id ),
	modified_content clob,
	review_status    varchar2(20) default 'pending',
	submitted_date   date default sysdate,
	review_date      date
);

--�����û����ֱ�
create table userpoints (
	points_id    number
		generated by default as identity start with 1
	primary key,
	user_id      number
		references users ( user_id ),
	points       number default 0,
	last_updated date default sysdate
);

--�����û����
create table usergroups (
	group_id     number
		generated by default as identity start with 1
	primary key,
	group_name   varchar2(100),
	creator_id   number
		references users ( user_id ),
	created_date date default sysdate
);

--����������־��
create table carelogs (
	log_id        number
		generated by default as identity start with 1
	primary key,
	user_id       number
		references users ( user_id ),
	plant_id      number
		references plants ( plant_id ),
	care_activity clob,
	log_date      date default sysdate
);

--�����û�������
create table feedbacks (
	feedback_id      number
		generated by default as identity start with 1
	primary key,
	user_id          number
		references users ( user_id ),
	feedback_content clob,
	submitted_date   date default sysdate
);

--����ֲ��ͼƬ��
create table plantimages (
	image_id           number
		generated by default as identity start with 1
	primary key,
	plant_id           number
		references plants ( plant_id ),
	user_id            number
		references users ( user_id ),
	image_url          varchar2(255),
	recognition_result clob,
	diagnosis_result   clob,
	upload_date        date default sysdate
);

--�������������Ա�
create table plantregionsuitability (
	suitability_id number
		generated by default as identity start with 1
	primary key,
	plant_id       number
		references plants ( plant_id ),
	region_name    varchar2(100),
	suitability    varchar2(255)
);

--�����û����־��
create table useractivitylogs (
	log_id               number
		generated by default as identity start with 1
	primary key,
	user_id              number
		references users ( user_id ),
	activity_type        varchar2(100),
	activity_description clob,
	activity_date        date default sysdate
);

--�����������ѷ����
create table carereminders (
	reminder_id   number
		generated by default as identity start with 1
	primary key,
	plant_id      number
		references plants ( plant_id ),
	user_id       number
		references users ( user_id ),
	reminder_text varchar2(255),
	reminder_date date,
	is_active     char(1) default 'Y'
);

--�����в�ҩ��
create table medicinalherbs (
	herb_id              number
		generated by default as identity start with 1
	primary key,
	plant_id             number
		references plants ( plant_id ),
	medicinal_properties clob,
	usage_instructions   clob
);