--�����û���
CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    registration_date DATE DEFAULT SYSDATE,
    user_status VARCHAR2(20) DEFAULT 'active',
    user_role VARCHAR2(20) DEFAULT 'user',
    language_preference VARCHAR2(20) DEFAULT 'chinese'
);

--����ֲ���
CREATE TABLE Plants (
    plant_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    common_name VARCHAR2(100),
    scientific_name VARCHAR2(100),
    category VARCHAR2(100),
    portrayal CLOB,
    growth_environment VARCHAR2(255),
    care_conditions CLOB
);

--����˽�ű�
CREATE TABLE Messages (
    message_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    sender_id NUMBER REFERENCES Users(user_id),
    receiver_id NUMBER REFERENCES Users(user_id),
    message_content CLOB,
    sent_date DATE DEFAULT SYSDATE
);

--�����ղر�
CREATE TABLE Favorites (
    favorite_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    plant_id NUMBER REFERENCES Plants(plant_id)
);
--�����ղر�
CREATE TABLE FavoritesArticles (
    favorite_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    article_id NUMBER REFERENCES Articles(article_id)
);

--�������º͹����
CREATE TABLE Articles (
    article_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    article_title VARCHAR2(200),
    article_content CLOB,
    publisher_id NUMBER REFERENCES Users(user_id),
    published_date DATE DEFAULT SYSDATE,
    article_type VARCHAR2(50) DEFAULT 'article'  -- 'article' or 'announcement'
);

--�������۱�
CREATE TABLE Comments (
    comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    article_id NUMBER REFERENCES Articles(article_id),
    comment_content CLOB,
    created_date DATE DEFAULT SYSDATE
);

--������˱�
CREATE TABLE Reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    plant_id NUMBER REFERENCES Plants(plant_id),
    submitter_id NUMBER REFERENCES Users(user_id),
    modified_content CLOB,
    review_status VARCHAR2(20) DEFAULT 'pending',
    submitted_date DATE DEFAULT SYSDATE,
    review_date DATE
);

--�����û����ֱ�
CREATE TABLE UserPoints (
    points_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    points NUMBER DEFAULT 0,
    last_updated DATE DEFAULT SYSDATE
);

--�����û����
CREATE TABLE UserGroups (
    group_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    group_name VARCHAR2(100),
    creator_id NUMBER REFERENCES Users(user_id),
    created_date DATE DEFAULT SYSDATE
);

--����������־��
CREATE TABLE CareLogs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    plant_id NUMBER REFERENCES Plants(plant_id),
    care_activity CLOB,
    log_date DATE DEFAULT SYSDATE
);

--�����û�������
CREATE TABLE Feedbacks (
    feedback_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    feedback_content CLOB,
    submitted_date DATE DEFAULT SYSDATE
);

--����ֲ��ͼƬ��
CREATE TABLE PlantImages (
    image_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    plant_id NUMBER REFERENCES Plants(plant_id),
    user_id NUMBER REFERENCES Users(user_id),
    image_url VARCHAR2(255),
    recognition_result CLOB,
    diagnosis_result CLOB,
    upload_date DATE DEFAULT SYSDATE
);

--�������������Ա�
CREATE TABLE PlantRegionSuitability (
    suitability_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    plant_id NUMBER REFERENCES Plants(plant_id),
    region_name VARCHAR2(100),
    suitability VARCHAR2(255)
);

--�����û����־��
CREATE TABLE UserActivityLogs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    activity_type VARCHAR2(100),
    activity_description CLOB,
    activity_date DATE DEFAULT SYSDATE
);

--�����������ѷ����
CREATE TABLE CareReminders (
    reminder_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    plant_id NUMBER REFERENCES Plants(plant_id),
    user_id NUMBER REFERENCES Users(user_id),
    reminder_text VARCHAR2(255),
    reminder_date DATE,
    is_active CHAR(1) DEFAULT 'Y'
);

--�����в�ҩ��
CREATE TABLE MedicinalHerbs (
    herb_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    plant_id NUMBER REFERENCES Plants(plant_id),
    medicinal_properties CLOB,
    usage_instructions CLOB
);

--删除对应的文章时，删除相关评论
CREATE OR REPLACE TRIGGER Delete_Comments_Trigger
AFTER DELETE ON Articles
FOR EACH ROW
BEGIN
    DELETE FROM Comments WHERE article_id = :OLD.article_id;
END;
/

CREATE OR REPLACE TRIGGER Add_Article_P_Trigger
AFTER INSERT ON Articles
FOR EACH ROW
BEGIN
    -- 插入新的积分记录，给发布文章的用户增加 5 分
    INSERT INTO UserPoints (user_id, points, last_updated)
    VALUES (:NEW.publisher_id, 5, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER Add_Comment_P_Trigger
AFTER INSERT ON Comments
FOR EACH ROW
BEGIN
    -- 插入新的积分记录，给发表评论的用户增加 2 分
    INSERT INTO UserPoints (user_id, points, last_updated)
    VALUES (:NEW.user_id, 2, SYSDATE);
END;
/


