--创建用户表
CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    registration_date DATE DEFAULT SYSDATE,
    user_status VARCHAR2(20) DEFAULT 'active',
    user_role VARCHAR2(20) DEFAULT 'user',
    language_preference VARCHAR2(20) DEFAULT 'chinese'
);

--创建植物表
CREATE TABLE Plants (
    plant_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    common_name VARCHAR2(100),
    scientific_name VARCHAR2(100),
    category VARCHAR2(100),
    portrayal CLOB,
    growth_environment VARCHAR2(255),
    care_conditions CLOB
);

--创建评论表
CREATE TABLE Comments (
    comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    plant_id NUMBER REFERENCES Plants(plant_id),
    comment_content CLOB,
    created_date DATE DEFAULT SYSDATE
);

--创建私信表
CREATE TABLE Messages (
    message_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    sender_id NUMBER REFERENCES Users(user_id),
    receiver_id NUMBER REFERENCES Users(user_id),
    message_content CLOB,
    sent_date DATE DEFAULT SYSDATE
);

--创建收藏表
CREATE TABLE Favorites (
    favorite_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    plant_id NUMBER REFERENCES Plants(plant_id)
);

--创建文章和公告表
CREATE TABLE Articles (
    article_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    article_title VARCHAR2(200),
    article_content CLOB,
    publisher_id NUMBER REFERENCES Users(user_id),
    published_date DATE DEFAULT SYSDATE,
    article_type VARCHAR2(50) DEFAULT 'article'  -- 'article' or 'announcement'
);

--创建审核表
CREATE TABLE Reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    plant_id NUMBER REFERENCES Plants(plant_id),
    submitter_id NUMBER REFERENCES Users(user_id),
    modified_content CLOB,
    review_status VARCHAR2(20) DEFAULT 'pending',
    submitted_date DATE DEFAULT SYSDATE,
    review_date DATE
);

--创建用户积分表
CREATE TABLE UserPoints (
    points_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    points NUMBER DEFAULT 0,
    last_updated DATE DEFAULT SYSDATE
);

--创建用户组表
CREATE TABLE UserGroups (
    group_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    group_name VARCHAR2(100),
    creator_id NUMBER REFERENCES Users(user_id),
    created_date DATE DEFAULT SYSDATE
);

--创建养护日志表
CREATE TABLE CareLogs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    plant_id NUMBER REFERENCES Plants(plant_id),
    care_activity CLOB,
    log_date DATE DEFAULT SYSDATE
);

--创建用户反馈表
CREATE TABLE Feedbacks (
    feedback_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    feedback_content CLOB,
    submitted_date DATE DEFAULT SYSDATE
);

--创建植物图片表
CREATE TABLE PlantImages (
    image_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    plant_id NUMBER REFERENCES Plants(plant_id),
    user_id NUMBER REFERENCES Users(user_id),
    image_url VARCHAR2(255),
    recognition_result CLOB,
    diagnosis_result CLOB,
    upload_date DATE DEFAULT SYSDATE
);

--创建地区适宜性表
CREATE TABLE PlantRegionSuitability (
    suitability_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    plant_id NUMBER REFERENCES Plants(plant_id),
    region_name VARCHAR2(100),
    suitability VARCHAR2(255)
);

--创建用户活动日志表
CREATE TABLE UserActivityLogs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    activity_type VARCHAR2(100),
    activity_description CLOB,
    activity_date DATE DEFAULT SYSDATE
);

--创建养护提醒服务表
CREATE TABLE CareReminders (
    reminder_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    plant_id NUMBER REFERENCES Plants(plant_id),
    user_id NUMBER REFERENCES Users(user_id),
    reminder_text VARCHAR2(255),
    reminder_date DATE,
    is_active CHAR(1) DEFAULT 'Y'
);

--创建中草药表
CREATE TABLE MedicinalHerbs (
    herb_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 PRIMARY KEY,
    plant_id NUMBER REFERENCES Plants(plant_id),
    medicinal_properties CLOB,
    usage_instructions CLOB
);